language: groovy
jdk:
- oraclejdk8
env:
- GO_VERSION=1.9 GOROOT="/usr/lib/go-1.9" GOPATH="${TRAVIS_BUILD_DIR}/.go" PATH="/usr/lib/go-1.9/bin:${PATH}"
before_install:
- openssl aes-256-cbc -K $encrypted_86c85184f8a5_key -iv $encrypted_86c85184f8a5_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- sudo add-apt-repository -y ppa:gophers/archive
- sudo apt-get update -qq
- sudo apt-get install -qq xmlindent
- sudo apt-get install -qq golang-${GO_VERSION}-go
script:
- "./grailsw test-app unit: integration:"
- "./grailsw test-app functional: 'org.zenboot.portal.api.**.*' -inline"
#- echo "n" | ./grailsw run-app &
#- sleep 120
#- cd ./zenboot-scripts/internal/scripts/sanity-restcheck && ./010_sanity-restcheck.sh
#  && cd ../../../..
- ./grailsw war
- mkdir zenboot-cli/bin
- go get -d ./...
- GOOS=linux GOARCH=amd64 go build -o zenboot-cli/bin/zenboot-linux-amd64 zenboot-cli/zenboot.go
- GOOS=darwin GOARCH=amd64 go build -o zenboot-cli/bin/zenboot-darwin-amd64 zenboot-cli/zenboot.go
notifications:
  email:
  - k9ert@gmx.de
  - martin.sander@sap.com
  slack: yrpm:rDezlAPq20RKGIp10YUeHRnq
deploy:
  provider: releases
  api_key:
    secure: O/57Mm3YYVSeyPlOJYA0jbkmrGMP3Et3eYS12ztCG0S1Duna1/2Ni/v5h/1z1KYvFnV0mtWYwDHQSPJ89R1QUzVKARFkYAAgJt5IjgXnQmsygSxganE8uG37WDh/+XqODw6/oUQp6isJ6VeoIZ/TMfyfm8uM2Udh0AAdafcYEvI=
  skip_cleanup: true
  file:
  - target/zenboot.war
  - zenboot-cli/bin/zenboot-linux-amd64
  - zenboot-cli/bin/zenboot-darwin-amd64
  on:
    repo: hybris/zenboot
    tags: true
    all_branches: true
