language: groovy
jdk:
  - oraclejdk7
  - openjdk7
branches:
  only:
    - master
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq xmlindent
script: 
    - ./grailsw test-app
    - echo "n" | ./grailsw run-app &
    - sleep 120
    - cd ./zenboot-scripts/internal/scripts/sanity-restcheck && ./010_sanity-restcheck.sh 
