language: groovy
jdk:
- openjdk7
before_install:
- openssl aes-256-cbc -K $encrypted_86c85184f8a5_key -iv $encrypted_86c85184f8a5_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- sudo apt-get update -qq
- sudo apt-get install -qq xmlindent
script:
- ./grailsw test-app
- echo "n" | ./grailsw run-app &
- sleep 120
- cd ./zenboot-scripts/internal/scripts/sanity-restcheck && ./010_sanity-restcheck.sh
  && cd ../../../..
- ./grailsw war
notifications:
  email:
  - k9ert@gmx.de
  - pawel.oczadly@hybris.com
deploy:
  provider: releases
  api_key:
    secure: O/57Mm3YYVSeyPlOJYA0jbkmrGMP3Et3eYS12ztCG0S1Duna1/2Ni/v5h/1z1KYvFnV0mtWYwDHQSPJ89R1QUzVKARFkYAAgJt5IjgXnQmsygSxganE8uG37WDh/+XqODw6/oUQp6isJ6VeoIZ/TMfyfm8uM2Udh0AAdafcYEvI=
  skip_cleanup: true
  file: target/zenboot.war
  on:
    repo: hybris/zenboot
    tags: true
    all_branches: true
after_success:
- chmod 600 .travis/id_rsa
- ssh-add .travis/id_rsa
- sed -i 's/ADD http.*/ADD https:\/\/github.com\/hybris\/zenboot\/releases\/download\/v0.7.3\/zenboot.war \/home\/user\/tomcat7\/webapps\/zenboot.war/' Dockerfile
- git add Dockerfile
- git commit -m "Release and adapt Dockerfile"
- git push
